package ventanas.producto;

import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

// Controladores del Modelo Producto
import backend.model.Producto;
import backend.controller.ProductoCRUDImp;
import backend.controller.CategoriaTemp;

import java.util.List;

import javax.swing.JOptionPane;

/**
 *
 * @authors Rodrigo - Dayron - Liam
 */
public class ProductoVentana extends javax.swing.JFrame {

    /**
     * Creates new form ProductoVentana
     */
    // declare TableModel
    DefaultComboBoxModel CategoriaNombreModel = new DefaultComboBoxModel();
    List<String[]> categoriaList = new CategoriaTemp().getCategoryNameIdPairs();    
    DefaultTableModel tableProductosModel;
    ProductoCRUDImp dao = new ProductoCRUDImp();
    private List<Producto> productosLista;    
    
    private int privilegeLevel = 1;
    
    public ProductoVentana() {
        initComponents();
        initProductsTableModel();
        initCategoriaModel();
        setupTabbedPanesPrivileges();
    }

    public void setPrivilegeLevel(int value){
        this.privilegeLevel = value;
    }
    
    private void setupTabbedPanesPrivileges(){
        if (privilegeLevel!=1){
            this.jTabbedPane2.setEnabledAt(1, false);
            this.jTabbedPane2.setEnabledAt(2, false);        
        }
    }
    
    private void initCategoriaModel(){
        CategoriaIdLabel.setText(categoriaList.get(0)[0]);
        for (int k=0; k < categoriaList.size(); k++){
            String categoriaNombre = categoriaList.get(k)[1];
            CategoriaNombreModel.insertElementAt(categoriaNombre, k);            
        }
        CategoriaComboBox.setModel(CategoriaNombreModel);
        CategoriaComboBox.setSelectedIndex(0);
    }
    
    private void clearTable(){
        this.tableProductosModel.setRowCount(0);
    }
    
    private void refreshTableProducts(){
        clearTable();
        productosLista = dao.list();            
        for (Producto producto: productosLista){
            Object[] productoValues = {producto.getId(), producto.getNombre(), producto.getPrecioCompra(), producto.getCategoriaId(), producto.getStockActual(), producto.getUnidadMedida(), producto.getCantidadMedida()};
            this.tableProductosModel.addRow(productoValues);
        }          
    }
    
    private void initProductsTableModel(){
        String[] columnNames = {
                "Codigo", "Nombre", "Precio compra", "Categoria ID", "Stock actual", "U. Medida", "Cant. medida"};  
        tableProductosModel = new DefaultTableModel(null,columnNames);
        this.tabla.setModel(tableProductosModel);
        setupProductsTableRowsWidth();
        refreshTableProducts();
    }    
    private void setupProductsTableRowsWidth(){
        tabla.getColumnModel().getColumn(0).setPreferredWidth(30);
        tabla.getColumnModel().getColumn(1).setPreferredWidth(140);
        tabla.setRowHeight(30);
    }

    private boolean isInt(String text){
        try {
            int n = Integer.parseInt(text);
        } catch (NumberFormatException e) {
            return false;
        }
        return true;
    }
    
    private boolean isFLoat(String text){
        try {
            float n = Float.parseFloat(text);
        } catch (NumberFormatException e) {
            return false;
        }
        return true;
    }    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        PanelVer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        PanelAgregar = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NombreProductoLabel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DescripcionProductoLabel = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        CategoriaIdLabel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PrecioProductoLabel = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        StockInicialProductoLabel = new javax.swing.JTextField();
        CategoriaComboBox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        AgregarButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        CantidadMedidaProductoLabel = new javax.swing.JTextField();
        UnidadMedidaComboBox = new javax.swing.JComboBox<>();
        PanelEditarEliminar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 680));
        setMinimumSize(new java.awt.Dimension(1024, 680));

        jPanel5.setBackground(new java.awt.Color(127, 181, 255));
        jPanel5.setMaximumSize(new java.awt.Dimension(1024, 680));
        jPanel5.setMinimumSize(new java.awt.Dimension(1024, 680));
        jPanel5.setPreferredSize(new java.awt.Dimension(1024, 680));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Barlow Condensed", 2, 18)); // NOI18N

        PanelVer.setBackground(new java.awt.Color(232, 250, 254));
        PanelVer.setPreferredSize(new java.awt.Dimension(1024, 680));

        jLabel3.setFont(new java.awt.Font("Barlow Condensed", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("RESUMEN DE PRODUCTOS");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        limpiar.setBackground(new java.awt.Color(127, 181, 255));
        limpiar.setFont(new java.awt.Font("Barlow Condensed", 1, 24)); // NOI18N
        limpiar.setForeground(new java.awt.Color(255, 255, 255));
        limpiar.setText("Actualizar");
        limpiar.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 10, 2, 10));
        limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Precio de compra", "Categoría ID", "Stock actual", "Unidad de medida", "Cantidad medida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(1).setResizable(false);
            tabla.getColumnModel().getColumn(2).setResizable(false);
            tabla.getColumnModel().getColumn(3).setResizable(false);
            tabla.getColumnModel().getColumn(4).setResizable(false);
            tabla.getColumnModel().getColumn(5).setResizable(false);
            tabla.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout PanelVerLayout = new javax.swing.GroupLayout(PanelVer);
        PanelVer.setLayout(PanelVerLayout);
        PanelVerLayout.setHorizontalGroup(
            PanelVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVerLayout.createSequentialGroup()
                .addGroup(PanelVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelVerLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelVerLayout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(limpiar)
                .addGap(440, 440, 440))
        );
        PanelVerLayout.setVerticalGroup(
            PanelVerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Ver", PanelVer);

        PanelAgregar.setBackground(new java.awt.Color(232, 250, 254));

        jLabel6.setFont(new java.awt.Font("Barlow Condensed SemiBold", 1, 22)); // NOI18N
        jLabel6.setText("CREAR PRODUCTOS");

        jLabel2.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel2.setText("Nombre:");

        NombreProductoLabel.setFont(new java.awt.Font("Barlow", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel7.setText("Descripcion:");

        DescripcionProductoLabel.setColumns(8);
        DescripcionProductoLabel.setFont(new java.awt.Font("Barlow", 0, 16)); // NOI18N
        DescripcionProductoLabel.setRows(5);
        jScrollPane1.setViewportView(DescripcionProductoLabel);

        jLabel8.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel8.setText("Categoría:");

        CategoriaIdLabel.setEditable(false);
        CategoriaIdLabel.setFont(new java.awt.Font("Barlow", 0, 16)); // NOI18N
        CategoriaIdLabel.setText("102");
        CategoriaIdLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));
        CategoriaIdLabel.setMaximumSize(new java.awt.Dimension(80, 24));
        CategoriaIdLabel.setMinimumSize(new java.awt.Dimension(80, 24));
        CategoriaIdLabel.setPreferredSize(new java.awt.Dimension(80, 24));

        jLabel9.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel9.setText("Precio de compra:");

        PrecioProductoLabel.setFont(new java.awt.Font("Barlow", 0, 16)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel10.setText("Stock inicial:");

        StockInicialProductoLabel.setFont(new java.awt.Font("Barlow", 0, 16)); // NOI18N
        StockInicialProductoLabel.setText("0");

        CategoriaComboBox.setFont(new java.awt.Font("Barlow", 0, 16)); // NOI18N
        CategoriaComboBox.setForeground(java.awt.Color.white);
        CategoriaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analgésico", "Vitamina D", " " }));
        CategoriaComboBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CategoriaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaComboBoxActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel14.setText("Unidad medida:");

        AgregarButton.setBackground(new java.awt.Color(79, 132, 255));
        AgregarButton.setFont(new java.awt.Font("Barlow Condensed", 1, 18)); // NOI18N
        AgregarButton.setForeground(new java.awt.Color(255, 255, 255));
        AgregarButton.setText("AGREGAR");
        AgregarButton.setBorder(null);
        AgregarButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AgregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarButtonActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(127, 181, 255));
        jButton3.setFont(new java.awt.Font("Barlow Condensed", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("LIMPIAR");
        jButton3.setBorder(null);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel15.setText("Id:");

        jPanel1.setLayout(new java.awt.GridLayout(2, 3));

        jLabel16.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel16.setText("Cantidad medida:");

        CantidadMedidaProductoLabel.setFont(new java.awt.Font("Barlow", 0, 16)); // NOI18N

        UnidadMedidaComboBox.setFont(new java.awt.Font("Barlow", 0, 16)); // NOI18N
        UnidadMedidaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "unidad", "gramo", "miligramo", "litro", "mililitro" }));

        javax.swing.GroupLayout PanelAgregarLayout = new javax.swing.GroupLayout(PanelAgregar);
        PanelAgregar.setLayout(PanelAgregarLayout);
        PanelAgregarLayout.setHorizontalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                .addGap(327, 327, 327)
                                .addComponent(AgregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel8))
                                .addGap(19, 19, 19)
                                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(StockInicialProductoLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PrecioProductoLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CategoriaComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CategoriaIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgregarLayout.createSequentialGroup()
                                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NombreProductoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(74, 74, 74))
                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)))
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgregarLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAgregarLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(43, 43, 43)))
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(UnidadMedidaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CantidadMedidaProductoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(121, 121, 121))
        );
        PanelAgregarLayout.setVerticalGroup(
            PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAgregarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(PanelAgregarLayout.createSequentialGroup()
                                .addComponent(NombreProductoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(CategoriaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CategoriaIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(24, 24, 24)
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(PrecioProductoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(StockInicialProductoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelAgregarLayout.createSequentialGroup()
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(UnidadMedidaComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(CantidadMedidaProductoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(PanelAgregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AgregarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jTabbedPane2.addTab("Agregar", PanelAgregar);

        PanelEditarEliminar.setBackground(new java.awt.Color(232, 250, 254));
        PanelEditarEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Barlow Condensed SemiBold", 1, 22)); // NOI18N
        jLabel1.setText("EDITAR / ELIMINAR PRODUCTO");
        PanelEditarEliminar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 24, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "               SELECCIÓN PRODUCTO", "PARACETAMOL" }));
        PanelEditarEliminar.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 320, 53));

        jLabel11.setBackground(new java.awt.Color(147, 176, 255));
        jLabel11.setForeground(new java.awt.Color(153, 153, 153));
        jLabel11.setText("BUSQUE EL PRODUCTO QUE DESEA EDITAR");
        PanelEditarEliminar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Barlow Condensed Light", 0, 17)); // NOI18N
        jButton2.setText("ELIMINAR");
        PanelEditarEliminar.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 150, 50));

        jLabel4.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel4.setText("Cantidad de Medida");
        PanelEditarEliminar.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel12.setText("Stock Inicial");
        PanelEditarEliminar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, 20));

        jLabel13.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel13.setText("Nombre");
        PanelEditarEliminar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jLabel17.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel17.setText("ID");
        PanelEditarEliminar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, -1, -1));

        jLabel18.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel18.setText("Precio de Compra");
        PanelEditarEliminar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        jLabel19.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel19.setText("Unidad de Medida");
        PanelEditarEliminar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, -1, -1));
        PanelEditarEliminar.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 180, -1));
        PanelEditarEliminar.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 180, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        PanelEditarEliminar.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 260, 120));

        jTextField3.setBackground(new java.awt.Color(242, 242, 242));
        PanelEditarEliminar.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 60, -1));
        PanelEditarEliminar.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 180, -1));
        PanelEditarEliminar.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 180, -1));

        jLabel20.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel20.setText("Descripción");
        PanelEditarEliminar.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        PanelEditarEliminar.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 260, -1));

        jButton4.setBackground(new java.awt.Color(155, 210, 242));
        jButton4.setFont(new java.awt.Font("Barlow Condensed Light", 0, 17)); // NOI18N
        jButton4.setText("BUSCAR");
        PanelEditarEliminar.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 150, 50));

        jButton5.setBackground(new java.awt.Color(155, 210, 242));
        jButton5.setFont(new java.awt.Font("Barlow Condensed Light", 0, 17)); // NOI18N
        jButton5.setText("EDITAR");
        PanelEditarEliminar.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, 150, 50));

        jLabel21.setFont(new java.awt.Font("Barlow Condensed", 3, 17)); // NOI18N
        jLabel21.setText("Categoría");
        PanelEditarEliminar.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ANALGÉSICO", " " }));
        PanelEditarEliminar.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 150, -1));

        jTabbedPane2.addTab("Editar / Eliminar", PanelEditarEliminar);

        jLabel5.setFont(new java.awt.Font("Barlow Condensed", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("SECCIÓN PRODUCTOS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addComponent(jLabel5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 1030, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        refreshTableProducts();
    }//GEN-LAST:event_limpiarActionPerformed

    private String validateFields(String nombre, String descripcion, String categoria, String precio, String stock, String cantidadMedida ){
        if (nombre.isBlank()||descripcion.isBlank()||categoria.isBlank()||precio.isBlank()||stock.isBlank()||cantidadMedida.isBlank()){
            return "Los campos no pueden estar vacios";
        }
        else if (nombre.length()>24){
            return "El Nombre no puede ser mas de 24 caracteres";
        }
        else if(descripcion.length()>255){
            return "La Descripcion no puede ser mas de 255 caracteres";        
        }
        else if(!(isInt(categoria))){
            return "Categoria invalida";
        }
        else if(!(isFLoat(precio))){
            return "El Precio debe ser decimal";
        }
        else if(!(isInt(stock))){
            return "El Stock debe ser entero";
        }
        else if(!(isInt(cantidadMedida))){
            return "La Cantidad medida debe ser entero";
        }
        else{
            return "";
        }
    }
    
    private void AgregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarButtonActionPerformed
        Producto prod = new Producto();    
        String entNombre = NombreProductoLabel.getText();
        String entDescripcion = DescripcionProductoLabel.getText();
        String entCategoriaId = CategoriaIdLabel.getText();
        String entPrecioCompra = PrecioProductoLabel.getText();
        String entStockInicial = StockInicialProductoLabel.getText();
        String entUnidadMedida = UnidadMedidaComboBox.getSelectedItem().toString(); 
        String entCantidadMedida = CantidadMedidaProductoLabel.getText();
        String errorField = validateFields(entNombre, entDescripcion, entCategoriaId, entPrecioCompra, entStockInicial, entCantidadMedida);
        if (!"".equals(errorField)){ /* !="" */
            JOptionPane.showMessageDialog(null, errorField, "Validacion de campos",0);
        }else{
            prod.setNombre(entNombre);        
            prod.setDescripcion(entDescripcion);
            prod.setPrecioCompra(Float.parseFloat(entPrecioCompra));
            prod.setCategoriaId(Integer.parseInt(entCategoriaId));
            prod.setStockActual(Integer.parseInt(entStockInicial));
            prod.setUnidadMedida(entUnidadMedida);
            prod.setCantidadMedida(Integer.parseInt(entCantidadMedida));                
            dao.save(prod);      
            JOptionPane.showMessageDialog(null, "Producto agregado correctamente!", "Farmacia Tu Salud",1);            
        }
    }//GEN-LAST:event_AgregarButtonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        NombreProductoLabel.setText("");
        DescripcionProductoLabel.setText("");
        StockInicialProductoLabel.setText("0");
        CantidadMedidaProductoLabel.setText("");
        CategoriaComboBox.setSelectedIndex(0);
        UnidadMedidaComboBox.setSelectedIndex(0);
        PrecioProductoLabel.setText("");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CategoriaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaComboBoxActionPerformed
        int catIndex = CategoriaComboBox.getSelectedIndex();
        String catDynamicId = categoriaList.get(catIndex)[0];
        CategoriaIdLabel.setText(catDynamicId);
    }//GEN-LAST:event_CategoriaComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarButton;
    private javax.swing.JTextField CantidadMedidaProductoLabel;
    private javax.swing.JComboBox<String> CategoriaComboBox;
    private javax.swing.JTextField CategoriaIdLabel;
    private javax.swing.JTextArea DescripcionProductoLabel;
    private javax.swing.JTextField NombreProductoLabel;
    private javax.swing.JPanel PanelAgregar;
    private javax.swing.JPanel PanelEditarEliminar;
    private javax.swing.JPanel PanelVer;
    private javax.swing.JTextField PrecioProductoLabel;
    private javax.swing.JTextField StockInicialProductoLabel;
    private javax.swing.JComboBox<String> UnidadMedidaComboBox;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton limpiar;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
